[namelist:base_mesh]
f_lat_deg=45.0
fplane=.false.
geometry='planar'

[namelist:extrusion]
domain_height=20.0e3
number_of_layers=40

[namelist:formulation]
l_multigrid=.false.
moisture_formulation='traditional'
moisture_in_solver=.true.
rotating=.false.
solver_moisture_conservation=.true.
theta_moist_source=.true.

[namelist:helmholtz_solver]
fail_on_non_converged=.true.
gcrk=18
method='bicgstab'
monitor_convergence=.true.
preconditioner='tridiagonal'
si_pressure_a_tol=1.0e-6

[namelist:idealised]
test='specified_profiles'

[namelist:initial_temperature]
profile_data=300.0,240.0,260.0
profile_heights=2.0e3,16.0e3,20.0e3
profile_size=3
profile_variable='absolute'

[namelist:initial_vapour]
profile_data=0.9,0.7,0.1,0.01
profile_heights=1.5e3,4.0e3,10.0e3,20.0e3
profile_size=3
profile_variable='rh'

[namelist:initial_wind]
profile='constant_uv'
smp_init_wind=.true.

[namelist:io]
diagnostic_frequency=10

[!!namelist:multigrid]

[namelist:partitioning]
partitioner='planar'

[namelist:transport]
panel_edge_treatment='none'
