[namelist:formulation]
solver_moisture_conservation=.true.

[namelist:timestepping]
inner_iterations_bdf2=1,1
!!inner_iterations_si=2,2
inner_iterations_tr=2,1
method='tr_bdf2'
!!tau_r=1.0
!!tau_t=1.0
!!tau_u=0.55

[namelist:radiation]
n_radstep=5

[namelist:transport]
dep_pt_stencil_extent=10
